spring.datasource.url=jdbc:mysql://switchbackproxy.rlwy.net:30691/railway/nutribalance
spring.datasource.username=root
spring.datasource.password=pwbDXeukIcjXagAdsqtcmFdvNPHulrwQ

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
